apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
        monitoring: enabled # this is very important to have and will be discuessed later
    spec:
      containers:
        - name: app-1
          image: Philcz16/goapp:latest
          ports:
            - containerPort: 3000
              name: http-metrics
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: app-1-service
  labels:
    monitoring: enabled # this is very important to have and will be discuessed later
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-metrics
      name: http-metrics
  selector:
    app: app-1